// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Simple Auth API
 *
 * A RESTful API service that handles user authentication including signup, signin, and password reset functionality.
 *
 * API version: 1.0.0
 * Contact: support@example.com
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/PhyuSinKhantAung/go-auth-server/go"
)

func main() {
	log.Printf("Server started")

	AuthenticationAPIService := openapi.NewAuthenticationAPIService()
	AuthenticationAPIController := openapi.NewAuthenticationAPIController(AuthenticationAPIService)

	router := openapi.NewRouter(AuthenticationAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
