// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Simple Auth API
 *
 * A RESTful API service that handles user authentication including signup, signin, and password reset functionality.
 *
 * API version: 1.0.0
 * Contact: support@example.com
 */

package openapi

import (
	"context"
	"net/http"
)



// AuthenticationAPIRouter defines the required methods for binding the api requests to a responses for the AuthenticationAPI
// The AuthenticationAPIRouter implementation should parse necessary information from the http request,
// pass the data to a AuthenticationAPIServicer to perform the required actions, then write the service results to the http response.
type AuthenticationAPIRouter interface { 
	SignupPost(http.ResponseWriter, *http.Request)
	SigninPost(http.ResponseWriter, *http.Request)
	ResetPasswordPost(http.ResponseWriter, *http.Request)
}


// AuthenticationAPIServicer defines the api actions for the AuthenticationAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type AuthenticationAPIServicer interface { 
	SignupPost(context.Context, SignupPostRequest) (ImplResponse, error)
	SigninPost(context.Context, SigninPostRequest) (ImplResponse, error)
	ResetPasswordPost(context.Context, ResetPasswordPostRequest) (ImplResponse, error)
}
