// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Simple Auth API
 *
 * A RESTful API service that handles user authentication including signup, signin, and password reset functionality.
 *
 * API version: 1.0.0
 * Contact: support@example.com
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// AuthenticationAPIService is a service that implements the logic for the AuthenticationAPIServicer
// This service should implement the business logic for every endpoint for the AuthenticationAPI API.
// Include any external packages or services that will be required by this service.
type AuthenticationAPIService struct {
}

// NewAuthenticationAPIService creates a default api service
func NewAuthenticationAPIService() *AuthenticationAPIService {
	return &AuthenticationAPIService{}
}

// SignupPost - User sign up
func (s *AuthenticationAPIService) SignupPost(ctx context.Context, signupPostRequest SignupPostRequest) (ImplResponse, error) {
	// TODO - update SignupPost with the required logic for this service method.
	// Add api_authentication_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, {}) or use other options such as http.Ok ...
	// return Response(201, nil),nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("SignupPost method not implemented")
}

// SigninPost - User sign in
func (s *AuthenticationAPIService) SigninPost(ctx context.Context, signinPostRequest SigninPostRequest) (ImplResponse, error) {
	// TODO - update SigninPost with the required logic for this service method.
	// Add api_authentication_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, SigninPost200Response{}) or use other options such as http.Ok ...
	// return Response(200, SigninPost200Response{}), nil

	// TODO: Uncomment the next line to return response Response(401, {}) or use other options such as http.Ok ...
	// return Response(401, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("SigninPost method not implemented")
}

// ResetPasswordPost - Reset user password
func (s *AuthenticationAPIService) ResetPasswordPost(ctx context.Context, resetPasswordPostRequest ResetPasswordPostRequest) (ImplResponse, error) {
	// TODO - update ResetPasswordPost with the required logic for this service method.
	// Add api_authentication_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	// return Response(200, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("ResetPasswordPost method not implemented")
}
