// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Simple Auth API
 *
 * A RESTful API service that handles user authentication including signup, signin, and password reset functionality.
 *
 * API version: 1.0.0
 * Contact: support@example.com
 */

package openapi




// SigninPostRequest - Request payload for user sign in
type SigninPostRequest struct {

	// User's email address
	Email string `json:"email"`

	// User's password
	Password string `json:"password"`
}

// AssertSigninPostRequestRequired checks if the required fields are not zero-ed
func AssertSigninPostRequestRequired(obj SigninPostRequest) error {
	elements := map[string]interface{}{
		"email": obj.Email,
		"password": obj.Password,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertSigninPostRequestConstraints checks if the values respects the defined constraints
func AssertSigninPostRequestConstraints(obj SigninPostRequest) error {
	return nil
}
