// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Simple Auth API
 *
 * A RESTful API service that handles user authentication including signup, signin, and password reset functionality.
 *
 * API version: 1.0.0
 * Contact: support@example.com
 */

package openapi




// SignupPostRequest - Request payload for user registration
type SignupPostRequest struct {

	// Email address for the new user account
	Email string `json:"email"`

	// Password for the new user account (minimum 6 characters)
	Password string `json:"password"`
}

// AssertSignupPostRequestRequired checks if the required fields are not zero-ed
func AssertSignupPostRequestRequired(obj SignupPostRequest) error {
	elements := map[string]interface{}{
		"email": obj.Email,
		"password": obj.Password,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertSignupPostRequestConstraints checks if the values respects the defined constraints
func AssertSignupPostRequestConstraints(obj SignupPostRequest) error {
	return nil
}
