// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Simple Auth API
 *
 * A RESTful API service that handles user authentication including signup, signin, and password reset functionality.
 *
 * API version: 1.0.0
 * Contact: support@example.com
 */

package openapi




// ResetPasswordPostRequest - Request payload for password reset
type ResetPasswordPostRequest struct {

	// Email address of the user requesting password reset
	Email string `json:"email"`
}

// AssertResetPasswordPostRequestRequired checks if the required fields are not zero-ed
func AssertResetPasswordPostRequestRequired(obj ResetPasswordPostRequest) error {
	elements := map[string]interface{}{
		"email": obj.Email,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertResetPasswordPostRequestConstraints checks if the values respects the defined constraints
func AssertResetPasswordPostRequestConstraints(obj ResetPasswordPostRequest) error {
	return nil
}
